/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppTemplatesRouteImport } from './routes/_app/templates'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppEditorRouteImport } from './routes/_app/editor'
import { Route as AppAtsRouteImport } from './routes/_app/ats'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppEditorRoute = AppEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => AppRoute,
} as any)
const AppAtsRoute = AppAtsRouteImport.update({
  id: '/ats',
  path: '/ats',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/ats': typeof AppAtsRoute
  '/editor': typeof AppEditorRoute
  '/settings': typeof AppSettingsRoute
  '/templates': typeof AppTemplatesRoute
}
export interface FileRoutesByTo {
  '/ats': typeof AppAtsRoute
  '/editor': typeof AppEditorRoute
  '/settings': typeof AppSettingsRoute
  '/templates': typeof AppTemplatesRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/ats': typeof AppAtsRoute
  '/_app/editor': typeof AppEditorRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/templates': typeof AppTemplatesRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ats' | '/editor' | '/settings' | '/templates'
  fileRoutesByTo: FileRoutesByTo
  to: '/ats' | '/editor' | '/settings' | '/templates' | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/ats'
    | '/_app/editor'
    | '/_app/settings'
    | '/_app/templates'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/templates': {
      id: '/_app/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/editor': {
      id: '/_app/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof AppEditorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ats': {
      id: '/_app/ats'
      path: '/ats'
      fullPath: '/ats'
      preLoaderRoute: typeof AppAtsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAtsRoute: typeof AppAtsRoute
  AppEditorRoute: typeof AppEditorRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAtsRoute: AppAtsRoute,
  AppEditorRoute: AppEditorRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTemplatesRoute: AppTemplatesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
